services:
  - type: web
    name: shopit
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn shopit.wsgi:application --preload --log-file -"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
