services:
  - type: web
    name: shopit-frontend
    env: static
    buildCommand: cd shopit_app && npm install && npm run build
    staticPublishPath: ./shopit_app/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 